### ISSUE TITLE
Suggest creating an Angular 1 branch

### ISSUE THREAD

**Issue by tomwayson** [morrissinger/es6-scaffold#1]
I thought your blog post, gist, and this repo were very helpful in getting System.js/JSPM set up with Angular 1 - thank you!

However, it was still a bit of work to figure out where to put all the files in the gist (esp the html loader). Also, when I ran jspm to install Angular and UI Router, I was prompted to update the JSPM version.

So once I got it all up and running, I thought I would create [an Angular 1 branch in my fork](https://github.com/tomwayson/es6-scaffold/tree/angular-1) that has all the working pieces in place along w/ a README that gives step by step instructions to run the app. I don't want to PR that back to your master b/c I understand that you use this scaffold for other types of projects (Aurelia, etc). However, I thought it would be a good idea for you to create your own angular-1 branch so readers of the blog post can get up and running more quickly than I did.

If you do create that branch, and I will gladly PR my set up there if you'd like. Just let me know.

**Comment by morrissinger** [comment]
@tomwayson, I really appreciate the thought that went into this issue. I would be glad to review / merge your contributions into my newly created [angular-1](https://github.com/morrissinger/es6-scaffold/tree/angular-1) branch.

**Comment by tomwayson** [comment]
resolved via #2, see:

https://github.com/morrissinger/es6-scaffold/tree/angular-1
